language: node_js

install:
    - yarn install
    
script:
    - yarn lint
    - yarn test
    - yarn build

before_deploy: "echo 'Deploying: start'"

deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
  on:
    tags: true
    
after_deploy: "echo 'Deploying: finish'"